import Head from "next/head";
import Header from "../components/Header"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.shareicon.net/data/2015/07/26/75394_hulu_512x512.png"
        />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}

      {/* Results */}
    </div>
  );
}
