import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  console.log(results);

  return (
    <div>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://www.shareicon.net/data/2015/07/26/75394_hulu_512x512.png"
        />
      </Head>

      <Header />

      <Nav />

      <Results results={results} />
    </div>
  );
}

// code below shows this page and only this page is for server side rendering. This server render happens first before above client render

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
